language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - pypy
# command to install dependencies, e.g. pip install -r requirements.txt
# --use-mirrors
#install: pip install gitpython
#install: echo
# # command to run tests, e.g. python setup.py test
script:  python run_tests.py

